
# Use bash as the shell when executing a rule's recipe. For more details:
# https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html
SHELL := bash


.PHONY: all
all:


.PHONY: init
init:


.PHONY: setup
setup:


.PHONY: check
check:


.PHONY: test
test:


.PHONY: build build-docker
build:
build-docker:


.PHONY: docs
docs:


.PHONY: clean
clean:


.PHONY: nuke nuke-caches
nuke-caches:
nuke:
