services:

  # https://hub.docker.com/_/postgres/
  postgres-db:
    image: fullstack-template-backend-pg:0.0.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template_db
    healthcheck:
      test: pg_isready --username postgres --dbname template_db
      interval: 1s
      timeout: 5s
      retries: 10

  # https://hub.docker.com/r/postgrest/postgrest
  postgrest:
    image: postgrest/postgrest:v14.0@sha256:f8176256ad55a794a61ee6d76d00121635fac4d63bb3d51594e5ed6790f91c72
    ports:
    - 3000:3000
    environment:
      # https://docs.postgrest.org/en/stable/references/configuration.html
      PGRST_DB_URI: postgres://postgres:postgres@postgres-db:5432/template_db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3001
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_DB_SCHEMAS: api
      PGRST_JWT_SECRET: cLrngXnioRTsqo2vBKqiEPCN467PrrRl
      # PGRST_OPENAPI_SERVER_PROXY_URI:
      PGRST_OPENAPI_MODE: ignore-privileges
      PGRST_OPENAPI_SECURITY_ACTIVE: true
      # PGRST_ADMIN_SERVER_HOST: postgres-db
      # PGRST_ADMIN_SERVER_PORT: 3033
    healthcheck:
      # https://docs.postgrest.org/en/stable/references/admin_server.html#health-check
      # https://github.com/PostgREST/postgrest/discussions/3854
      disable: true

  # https://hub.docker.com/r/swaggerapi/swagger-ui/
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.29.5@sha256:be10a20c795c09059cb1024a15b9649a08b949e9604c7fc316d9a88fa7eacdcd
    ports:
    - 3001:8080
    environment:
    - API_URL=http://localhost:3000/
