FROM python:3.13-alpine3.21@sha256:452682e4648deafe431ad2f2391d726d7c52f0ff291be8bd4074b10379bb89ff

# Copy over the migrations and configuration.
RUN mkdir -p /alembic/alembic
COPY alembic/ /alembic/alembic/
COPY alembic.ini /alembic/
COPY alembic-requirements.txt /alembic/

# Install Alembic and its dependencies.
RUN python -m pip install --require-hashes --requirement /alembic/alembic-requirements.txt

# Entrypoint to the container is running Alembic and quitting.
ENTRYPOINT ["python", "-m", "alembic", "-c", "/alembic/alembic.ini", "upgrade", "head"]
